/**
 * Generated by following the `empty-and-loading-states` skill.
 *
 * Archetype: an AI product chat thread. Demonstrates the three states this skill
 * cares about for a streaming UI: an **empty** state with suggested prompts, a
 * **loading** "assistant is typing" indicator (animated, with a polite aria-live
 * region), and rendered message bubbles. Wire to your model stream in the consumer.
 */
import { Sparkles } from "lucide-react";

import { cn } from "@/lib/utils";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";

type Message = { id: string; role: "user" | "assistant"; content: string };

const SUGGESTIONS = ["Summarize my last invoice", "Draft a release note", "Explain this error"];

function Bubble({ role, children }: { role: Message["role"]; children: React.ReactNode }) {
  const isUser = role === "user";
  return (
    <div className={cn("flex gap-3", isUser && "flex-row-reverse")}>
      <Avatar className="h-7 w-7 shrink-0">
        <AvatarFallback className={cn("text-[10px]", !isUser && "bg-violet-600 text-white")}>
          {isUser ? "You" : <Sparkles className="h-3.5 w-3.5" />}
        </AvatarFallback>
      </Avatar>
      <div
        className={cn(
          "max-w-[80%] rounded-2xl px-3.5 py-2 text-sm leading-relaxed",
          isUser ? "bg-primary text-primary-foreground" : "bg-muted",
        )}
      >
        {children}
      </div>
    </div>
  );
}

function TypingIndicator() {
  return (
    <div className="flex gap-3" aria-live="polite" aria-label="Assistant is typing">
      <Avatar className="h-7 w-7 shrink-0">
        <AvatarFallback className="bg-violet-600 text-white"><Sparkles className="h-3.5 w-3.5" /></AvatarFallback>
      </Avatar>
      <div className="flex items-center gap-1 rounded-2xl bg-muted px-4 py-3">
        {[0, 150, 300].map((delay) => (
          <span
            key={delay}
            className="h-1.5 w-1.5 animate-bounce rounded-full bg-muted-foreground/60"
            style={{ animationDelay: `${delay}ms` }}
          />
        ))}
      </div>
    </div>
  );
}

export function AiChatThread({ messages = [], pending }: { messages?: Message[]; pending?: boolean }) {
  if (messages.length === 0 && !pending) {
    return (
      <div className="flex flex-col items-center justify-center gap-4 py-16 text-center">
        <span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-600 to-indigo-600 text-white">
          <Sparkles className="h-6 w-6" aria-hidden />
        </span>
        <div>
          <p className="font-medium">Ask anything about your workspace</p>
          <p className="text-sm text-muted-foreground">I can summarize, draft, and dig through your data.</p>
        </div>
        <div className="flex flex-wrap justify-center gap-2">
          {SUGGESTIONS.map((s) => (
            <Button key={s} variant="outline" size="sm" className="rounded-full">{s}</Button>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {messages.map((m) => (
        <Bubble key={m.id} role={m.role}>{m.content}</Bubble>
      ))}
      {pending && <TypingIndicator />}
    </div>
  );
}
