/**
 * Generated by following the `empty-and-loading-states` skill.
 *
 * Demonstrates the four states every data view needs: loading (skeleton that
 * matches the real layout), empty (oriented with a CTA), error (with retry),
 * and the success list. One <DataView> switches between them.
 */
"use client";

import { AlertCircle, Inbox, Plus } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";

export function ListSkeleton() {
  return (
    <div className="space-y-3" aria-busy="true" aria-live="polite">
      {Array.from({ length: 5 }).map((_, i) => (
        <div key={i} className="flex items-center gap-3 rounded-lg border p-4">
          <Skeleton className="h-10 w-10 rounded-full" />
          <div className="flex-1 space-y-2">
            <Skeleton className="h-4 w-1/3" />
            <Skeleton className="h-3 w-1/2" />
          </div>
          <Skeleton className="h-8 w-16" />
        </div>
      ))}
    </div>
  );
}

export function EmptyState({ onCreate }: { onCreate?: () => void }) {
  return (
    <div className="flex flex-col items-center justify-center rounded-lg border border-dashed p-12 text-center">
      <Inbox className="h-10 w-10 text-muted-foreground" aria-hidden />
      <h3 className="mt-4 text-sm font-semibold">No invoices yet</h3>
      <p className="mt-1 max-w-sm text-sm text-muted-foreground">
        Create your first invoice and it’ll show up here.
      </p>
      <Button className="mt-4" onClick={onCreate}>
        <Plus className="mr-2 h-4 w-4" /> New invoice
      </Button>
    </div>
  );
}

export function ErrorState({ onRetry }: { onRetry?: () => void }) {
  return (
    <div className="flex flex-col items-center justify-center gap-3 rounded-lg border border-destructive/30 p-10 text-center">
      <AlertCircle className="h-8 w-8 text-destructive" aria-hidden />
      <p className="text-sm">Couldn’t load invoices.</p>
      <Button variant="outline" size="sm" onClick={onRetry}>
        Try again
      </Button>
    </div>
  );
}

type ViewState<T> =
  | { status: "loading" }
  | { status: "error" }
  | { status: "ready"; items: T[] };

export function DataView<T extends { id: string; label: string }>({
  state,
  onRetry,
  onCreate,
}: {
  state: ViewState<T>;
  onRetry?: () => void;
  onCreate?: () => void;
}) {
  if (state.status === "loading") return <ListSkeleton />;
  if (state.status === "error") return <ErrorState onRetry={onRetry} />;
  if (state.items.length === 0) return <EmptyState onCreate={onCreate} />;

  return (
    <ul className="space-y-2">
      {state.items.map((item) => (
        <li key={item.id} className="rounded-lg border p-4 text-sm">
          {item.label}
        </li>
      ))}
    </ul>
  );
}
