/**
 * Generated by following the `component-architecture` skill.
 *
 * Archetype: a Project-management Kanban board. Demonstrates a **compound component**
 * pattern (`Board` / `Board.Column` / `Board.Card`) so the layout reads declaratively,
 * with status-colored columns, label pills, assignee avatars, and accessible regions.
 * State/DnD wiring is left to the consumer — this is the presentational architecture.
 */
import { Plus } from "lucide-react";

import { cn } from "@/lib/utils";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

type Card = { id: string; title: string; label?: string; assignee?: string };

function Board({ children }: { children: React.ReactNode }) {
  return <div className="flex gap-4 overflow-x-auto pb-2">{children}</div>;
}

function Column({ title, accent, count, children }: { title: string; accent: string; count: number; children: React.ReactNode }) {
  return (
    <section aria-label={title} className="flex w-72 shrink-0 flex-col rounded-xl bg-muted/40">
      <header className="flex items-center justify-between px-3 py-2.5">
        <div className="flex items-center gap-2">
          <span className={cn("h-2 w-2 rounded-full", accent)} aria-hidden />
          <h3 className="text-sm font-medium">{title}</h3>
          <span className="tabular-nums text-xs text-muted-foreground">{count}</span>
        </div>
        <Button size="icon" variant="ghost" className="h-6 w-6" aria-label={`Add card to ${title}`}>
          <Plus className="h-4 w-4" />
        </Button>
      </header>
      <div className="flex flex-col gap-2 px-2 pb-2">{children}</div>
    </section>
  );
}

function TaskCard({ title, label, assignee }: Card) {
  return (
    <article className="rounded-lg border bg-background p-3 shadow-sm transition hover:shadow-md focus-within:ring-2 focus-within:ring-ring">
      {label && <Badge variant="secondary" className="mb-2 text-[11px]">{label}</Badge>}
      <p className="text-sm font-medium leading-snug">{title}</p>
      <div className="mt-3 flex items-center justify-between">
        <span className="text-xs text-muted-foreground">#{title.length * 7}</span>
        {assignee && (
          <Avatar className="h-6 w-6">
            <AvatarFallback className="text-[10px]">{assignee}</AvatarFallback>
          </Avatar>
        )}
      </div>
    </article>
  );
}

Board.Column = Column;
Board.Card = TaskCard;

export function KanbanBoard() {
  return (
    <Board>
      <Board.Column title="Backlog" accent="bg-slate-400" count={2}>
        <Board.Card id="1" title="Audit onboarding funnel" label="Research" assignee="PB" />
        <Board.Card id="2" title="Spec billing webhooks" label="Backend" assignee="AK" />
      </Board.Column>
      <Board.Column title="In progress" accent="bg-amber-500" count={1}>
        <Board.Card id="3" title="Build command palette" label="Frontend" assignee="JD" />
      </Board.Column>
      <Board.Column title="Done" accent="bg-emerald-500" count={1}>
        <Board.Card id="4" title="Dark mode tokens" label="Design" assignee="MR" />
      </Board.Column>
    </Board>
  );
}
