/**
 * Generated by following the `navigation-patterns` skill (⌘K command palette).
 *
 * Archetype: cross-cutting power-user navigation for any SaaS. Demonstrates a cmdk
 * palette opened with ⌘K / Ctrl+K, grouped + keyboard-navigable results, an icon per
 * action, inline shortcut hints, and an accessible empty state. Built on shadcn's
 * `Command` (which wires roving focus, type-ahead, and aria roles for you).
 */
"use client";

import * as React from "react";
import { CreditCard, LayoutDashboard, Plus, Search, Settings, UserPlus } from "lucide-react";

import {
  CommandDialog,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  CommandSeparator,
  CommandShortcut,
} from "@/components/ui/command";

type Action = { icon: React.ElementType; label: string; shortcut?: string; onSelect: () => void };

export function CommandPalette({ actions }: { actions?: { navigate: (to: string) => void; create: () => void } }) {
  const [open, setOpen] = React.useState(false);

  React.useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "k" && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        setOpen((v) => !v);
      }
    };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, []);

  const go = (to: string) => () => {
    setOpen(false);
    actions?.navigate(to);
  };

  const navItems: Action[] = [
    { icon: LayoutDashboard, label: "Go to Dashboard", shortcut: "G D", onSelect: go("/dashboard") },
    { icon: CreditCard, label: "Go to Billing", shortcut: "G B", onSelect: go("/billing") },
    { icon: Settings, label: "Go to Settings", shortcut: "G S", onSelect: go("/settings") },
  ];
  const quickActions: Action[] = [
    { icon: Plus, label: "Create project", shortcut: "C", onSelect: () => { setOpen(false); actions?.create(); } },
    { icon: UserPlus, label: "Invite teammate", onSelect: go("/settings/members") },
  ];

  return (
    <>
      {/* Trigger that mirrors the shortcut for discoverability */}
      <button
        onClick={() => setOpen(true)}
        className="inline-flex w-64 items-center gap-2 rounded-lg border bg-muted/40 px-3 py-1.5 text-sm text-muted-foreground hover:bg-muted"
      >
        <Search className="h-4 w-4" aria-hidden />
        <span className="flex-1 text-left">Search…</span>
        <kbd className="rounded border bg-background px-1.5 font-mono text-[11px]">⌘K</kbd>
      </button>

      <CommandDialog open={open} onOpenChange={setOpen}>
        <CommandInput placeholder="Type a command or search…" />
        <CommandList>
          <CommandEmpty>No results found.</CommandEmpty>
          <CommandGroup heading="Navigation">
            {navItems.map((a) => (
              <CommandItem key={a.label} onSelect={a.onSelect}>
                <a.icon className="mr-2 h-4 w-4" aria-hidden />
                <span>{a.label}</span>
                {a.shortcut && <CommandShortcut>{a.shortcut}</CommandShortcut>}
              </CommandItem>
            ))}
          </CommandGroup>
          <CommandSeparator />
          <CommandGroup heading="Actions">
            {quickActions.map((a) => (
              <CommandItem key={a.label} onSelect={a.onSelect}>
                <a.icon className="mr-2 h-4 w-4" aria-hidden />
                <span>{a.label}</span>
                {a.shortcut && <CommandShortcut>{a.shortcut}</CommandShortcut>}
              </CommandItem>
            ))}
          </CommandGroup>
        </CommandList>
      </CommandDialog>
    </>
  );
}
