/**
 * Generated by following the `dashboard-layout` skill (modern bento variant).
 *
 * Archetype: an Analytics SaaS overview. Demonstrates a responsive **bento grid**
 * with mixed tile spans, a gradient hero metric, KPI tiles with sign+arrow deltas
 * (never color alone), and tabular-nums for aligned figures. Drop real charts into
 * the placeholder slots.
 */
import { ArrowDownRight, ArrowUpRight, Sparkles } from "lucide-react";

import { cn } from "@/lib/utils";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

type Kpi = { label: string; value: string; delta: number };

const kpis: Kpi[] = [
  { label: "Sessions", value: "82,402", delta: 9.1 },
  { label: "Conversion", value: "3.84%", delta: 0.6 },
  { label: "Avg. order", value: "$128.40", delta: -2.3 },
];

function Delta({ value }: { value: number }) {
  const up = value >= 0;
  return (
    <span className={cn("inline-flex items-center gap-0.5 text-xs font-medium", up ? "text-emerald-600" : "text-rose-600")}>
      {up ? <ArrowUpRight className="h-3.5 w-3.5" aria-hidden /> : <ArrowDownRight className="h-3.5 w-3.5" aria-hidden />}
      <span className="tabular-nums">{Math.abs(value)}%</span>
    </span>
  );
}

export function AnalyticsBento({ trend, channels }: { trend?: React.ReactNode; channels?: React.ReactNode }) {
  return (
    <section className="grid auto-rows-[minmax(0,1fr)] grid-cols-2 gap-4 lg:grid-cols-4">
      {/* Hero metric — spans 2 cols, gradient surface */}
      <Card className="col-span-2 overflow-hidden border-0 bg-gradient-to-br from-violet-600 to-indigo-600 text-white lg:row-span-2">
        <CardHeader>
          <CardDescription className="flex items-center gap-1.5 text-violet-100">
            <Sparkles className="h-4 w-4" aria-hidden /> Revenue this month
          </CardDescription>
          <CardTitle className="text-4xl font-semibold tabular-nums">$418,920</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-violet-100">
            <span className="font-medium text-white">+14.2%</span> vs last month
          </p>
          <div className="mt-4 h-32 rounded-lg bg-white/10 ring-1 ring-inset ring-white/15">
            {trend ?? <div className="flex h-full items-center justify-center text-sm text-violet-100">Trend chart</div>}
          </div>
        </CardContent>
      </Card>

      {/* KPI tiles */}
      {kpis.map((k) => (
        <Card key={k.label}>
          <CardHeader className="pb-2">
            <CardDescription>{k.label}</CardDescription>
            <CardTitle className="text-2xl tabular-nums">{k.value}</CardTitle>
          </CardHeader>
          <CardContent>
            <Delta value={k.delta} />
          </CardContent>
        </Card>
      ))}

      {/* Channels — spans full width on small, 2 cols on large */}
      <Card className="col-span-2">
        <CardHeader className="flex-row items-center justify-between space-y-0">
          <CardTitle className="text-base">Top channels</CardTitle>
          <Badge variant="secondary">Live</Badge>
        </CardHeader>
        <CardContent>
          {channels ?? (
            <ul className="space-y-2 text-sm">
              {[
                { name: "Organic", pct: 42 },
                { name: "Direct", pct: 28 },
                { name: "Referral", pct: 18 },
              ].map((c) => (
                <li key={c.name} className="flex items-center gap-3">
                  <span className="w-20 text-muted-foreground">{c.name}</span>
                  <span className="h-2 flex-1 overflow-hidden rounded-full bg-muted">
                    <span className="block h-full rounded-full bg-violet-500" style={{ width: `${c.pct}%` }} />
                  </span>
                  <span className="w-10 text-right tabular-nums text-muted-foreground">{c.pct}%</span>
                </li>
              ))}
            </ul>
          )}
        </CardContent>
      </Card>
    </section>
  );
}
