/**
 * Generated by following the `dashboard-layout` skill.
 *
 * Demonstrates: a KPI row that reflows 1 → 2 → 4 columns, stat cards with
 * sign + arrow deltas (not color alone), and a main chart + side panel split.
 */
import { ArrowDown, ArrowUp } from "lucide-react";

import { cn } from "@/lib/utils";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

type Stat = { label: string; value: string; delta: number };

const stats: Stat[] = [
  { label: "MRR", value: "$24,580", delta: 12.5 },
  { label: "Active users", value: "1,429", delta: 4.2 },
  { label: "Churn", value: "2.1%", delta: -0.4 },
  { label: "Signups", value: "312", delta: 18.0 },
];

function StatCard({ label, value, delta }: Stat) {
  const up = delta >= 0;
  return (
    <Card>
      <CardHeader className="pb-2">
        <CardDescription>{label}</CardDescription>
        <CardTitle className="text-3xl tabular-nums">{value}</CardTitle>
      </CardHeader>
      <CardContent>
        <p className={cn("flex items-center gap-1 text-xs", up ? "text-emerald-600" : "text-destructive")}>
          {up ? <ArrowUp className="h-3 w-3" aria-hidden /> : <ArrowDown className="h-3 w-3" aria-hidden />}
          <span className="tabular-nums">{Math.abs(delta)}%</span>
          <span className="text-muted-foreground">vs last month</span>
        </p>
      </CardContent>
    </Card>
  );
}

export function DashboardOverview({ chart, activity }: { chart?: React.ReactNode; activity?: React.ReactNode }) {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">Overview</h1>
        <p className="text-sm text-muted-foreground">Your key metrics for this billing period.</p>
      </div>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {stats.map((s) => (
          <StatCard key={s.label} {...s} />
        ))}
      </div>

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-3">
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>Revenue</CardTitle>
            <CardDescription>Last 30 days</CardDescription>
          </CardHeader>
          <CardContent className="h-72">
            {chart ?? <div className="flex h-full items-center justify-center text-sm text-muted-foreground">Chart goes here</div>}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Recent activity</CardTitle>
          </CardHeader>
          <CardContent>
            {activity ?? <p className="text-sm text-muted-foreground">No recent activity.</p>}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
