/**
 * Generated by following the `auth-screens` skill (composing `forms-and-validation`).
 *
 * Demonstrates: a reusable auth shell, OAuth button + labelled divider, and the
 * security-conscious copy that avoids user enumeration.
 */
"use client";

import { Separator } from "@/components/ui/separator";
import { Button } from "@/components/ui/button";
import { SignInForm } from "../forms-and-validation/SignInForm";

function GoogleIcon({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" className={className} aria-hidden>
      <path fill="currentColor" d="M21.35 11.1H12v2.9h5.35c-.23 1.4-1.6 4.1-5.35 4.1A6 6 0 1 1 16 7.3l2-2A9 9 0 1 0 21.35 11.1Z" />
    </svg>
  );
}

export function SignInScreen({
  onSubmit,
  onOAuth,
}: {
  onSubmit?: (values: { email: string; password: string }) => Promise<{ ok: boolean }>;
  onOAuth?: (provider: "google") => void;
}) {
  return (
    <div className="flex min-h-screen items-center justify-center bg-muted/30 p-4">
      <div className="w-full max-w-sm">
        <div className="mb-6 text-center">
          <div className="mx-auto flex h-10 w-10 items-center justify-center rounded-lg bg-primary text-primary-foreground">
            <span className="text-lg font-bold">S</span>
          </div>
          <h1 className="mt-4 text-2xl font-semibold tracking-tight">Welcome back</h1>
          <p className="mt-1 text-sm text-muted-foreground">Sign in to your account to continue.</p>
        </div>

        <div className="rounded-lg border bg-card p-6 shadow-sm">
          <div className="grid gap-2">
            <Button variant="outline" className="w-full" onClick={() => onOAuth?.("google")}>
              <GoogleIcon className="mr-2 h-4 w-4" /> Continue with Google
            </Button>
          </div>

          <div className="relative my-5">
            <Separator />
            <span className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 bg-card px-2 text-xs uppercase text-muted-foreground">
              or
            </span>
          </div>

          <SignInForm onSubmit={onSubmit} />
        </div>

        <p className="mt-4 text-center text-sm text-muted-foreground">
          Don’t have an account?{" "}
          <a href="/signup" className="font-medium text-foreground hover:underline">
            Sign up
          </a>
        </p>
      </div>
    </div>
  );
}
