/**
 * Generated by following the `billing-and-pricing` skill.
 *
 * Demonstrates: a monthly/annual toggle with a savings badge, a single highlighted
 * "Most popular" plan to anchor choice, feature lists with checkmarks, and
 * tabular-nums prices that stay aligned.
 */
"use client";

import * as React from "react";
import { Check } from "lucide-react";

import { cn } from "@/lib/utils";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";

type Plan = {
  id: string;
  name: string;
  tagline: string;
  monthly: number;
  annual: number; // per-month price when billed annually
  features: string[];
  recommended?: boolean;
  cta?: string;
};

const plans: Plan[] = [
  {
    id: "free",
    name: "Free",
    tagline: "For trying things out.",
    monthly: 0,
    annual: 0,
    features: ["1 project", "Community support", "1 GB storage"],
    cta: "Get started",
  },
  {
    id: "pro",
    name: "Pro",
    tagline: "For growing teams.",
    monthly: 24,
    annual: 19,
    features: ["Unlimited projects", "Priority support", "100 GB storage", "Advanced analytics"],
    recommended: true,
    cta: "Start free trial",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    tagline: "For organizations at scale.",
    monthly: 99,
    annual: 79,
    features: ["SSO & SAML", "Dedicated support", "Unlimited storage", "Audit logs", "SLA"],
    cta: "Contact sales",
  },
];

export function PricingTable() {
  const [annual, setAnnual] = React.useState(true);

  return (
    <section className="mx-auto max-w-5xl px-4 py-12">
      <div className="mb-8 flex items-center justify-center gap-3">
        <span className={cn("text-sm", !annual && "font-medium")}>Monthly</span>
        <Switch checked={annual} onCheckedChange={setAnnual} aria-label="Toggle annual billing" />
        <span className={cn("text-sm", annual && "font-medium")}>
          Annual <Badge variant="success" className="ml-1">Save 20%</Badge>
        </span>
      </div>

      <div className="grid gap-6 md:grid-cols-3">
        {plans.map((plan) => (
          <Card key={plan.id} className={cn("relative flex flex-col", plan.recommended && "border-primary shadow-md")}>
            {plan.recommended && (
              <Badge className="absolute -top-3 left-1/2 -translate-x-1/2">Most popular</Badge>
            )}
            <CardHeader>
              <CardTitle>{plan.name}</CardTitle>
              <CardDescription>{plan.tagline}</CardDescription>
              <div className="mt-3">
                <span className="text-4xl font-bold tabular-nums">${annual ? plan.annual : plan.monthly}</span>
                <span className="text-muted-foreground">/mo</span>
              </div>
            </CardHeader>

            <CardContent className="flex-1">
              <ul className="space-y-2 text-sm">
                {plan.features.map((f) => (
                  <li key={f} className="flex items-start gap-2">
                    <Check className="mt-0.5 h-4 w-4 shrink-0 text-emerald-500" aria-hidden />
                    <span>{f}</span>
                  </li>
                ))}
              </ul>
            </CardContent>

            <CardFooter>
              <Button className="w-full" variant={plan.recommended ? "default" : "outline"}>
                {plan.cta ?? "Choose plan"}
              </Button>
            </CardFooter>
          </Card>
        ))}
      </div>
    </section>
  );
}
