/**
 * Generated by following the `billing-and-pricing` skill (metered/usage variant).
 *
 * Archetype: a Developer-tool / API platform usage panel. Demonstrates metered-plan
 * UI: per-resource progress meters that turn amber → red as they approach the cap,
 * an accessible <progress> semantic, a projected-overage callout, and an upgrade CTA.
 */
import { AlertTriangle } from "lucide-react";

import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type Meter = { label: string; used: number; limit: number; unit?: string };

const meters: Meter[] = [
  { label: "API requests", used: 824_000, limit: 1_000_000 },
  { label: "Seats", used: 9, limit: 10 },
  { label: "Storage", used: 47, limit: 50, unit: "GB" },
];

function tone(ratio: number) {
  if (ratio >= 0.9) return { bar: "bg-rose-500", text: "text-rose-600" };
  if (ratio >= 0.75) return { bar: "bg-amber-500", text: "text-amber-600" };
  return { bar: "bg-violet-500", text: "text-muted-foreground" };
}

const fmt = (n: number) => n.toLocaleString("en-US");

export function UsageMeter() {
  const nearLimit = meters.some((m) => m.used / m.limit >= 0.9);

  return (
    <Card>
      <CardHeader className="flex-row items-center justify-between space-y-0">
        <CardTitle className="text-base">Usage this period</CardTitle>
        <span className="text-xs text-muted-foreground">Resets Jul 1</span>
      </CardHeader>
      <CardContent className="space-y-5">
        {meters.map((m) => {
          const ratio = Math.min(m.used / m.limit, 1);
          const t = tone(ratio);
          return (
            <div key={m.label}>
              <div className="mb-1.5 flex items-baseline justify-between text-sm">
                <span className="font-medium">{m.label}</span>
                <span className={cn("tabular-nums", t.text)}>
                  {fmt(m.used)}
                  <span className="text-muted-foreground"> / {fmt(m.limit)}{m.unit ? ` ${m.unit}` : ""}</span>
                </span>
              </div>
              {/* native progress for semantics; visual bar layered on top */}
              <div className="relative h-2 overflow-hidden rounded-full bg-muted">
                <progress className="sr-only" value={m.used} max={m.limit} aria-label={`${m.label} usage`} />
                <span className={cn("absolute inset-y-0 left-0 rounded-full transition-all", t.bar)} style={{ width: `${ratio * 100}%` }} />
              </div>
            </div>
          );
        })}

        {nearLimit && (
          <div className="flex items-start gap-2 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm dark:border-amber-900 dark:bg-amber-950/40">
            <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" aria-hidden />
            <p className="text-amber-800 dark:text-amber-200">
              You're approaching your plan limits. Upgrade to avoid overage charges.
            </p>
          </div>
        )}

        <Button className="w-full">Upgrade plan</Button>
      </CardContent>
    </Card>
  );
}
