/**
 * Generated by following the `data-tables` skill.
 *
 * Archetype: a CRM deal pipeline table. Demonstrates a dense, scannable table with
 * stage badges (text + color, not color alone), owner avatars, right-aligned
 * tabular-nums currency, a weighted total in the header, and a sticky header row.
 * Sorting/filtering hooks are left to TanStack Table in the real component.
 */
import { cn } from "@/lib/utils";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

type Stage = "lead" | "qualified" | "proposal" | "won" | "lost";
type Deal = { id: string; company: string; owner: string; stage: Stage; value: number; closeDate: string };

const STAGE: Record<Stage, { label: string; className: string }> = {
  lead:      { label: "Lead",      className: "bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300" },
  qualified: { label: "Qualified", className: "bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-300" },
  proposal:  { label: "Proposal",  className: "bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300" },
  won:       { label: "Won",       className: "bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300" },
  lost:      { label: "Lost",      className: "bg-rose-100 text-rose-700 dark:bg-rose-950 dark:text-rose-300" },
};

const deals: Deal[] = [
  { id: "1", company: "Northwind", owner: "PB", stage: "proposal", value: 24000, closeDate: "Jun 18" },
  { id: "2", company: "Acme Corp", owner: "JD", stage: "qualified", value: 12500, closeDate: "Jun 24" },
  { id: "3", company: "Globex", owner: "AK", stage: "won", value: 48000, closeDate: "Jun 02" },
  { id: "4", company: "Initech", owner: "MR", stage: "lead", value: 6000, closeDate: "Jul 09" },
];

const usd = (n: number) => n.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

export function CrmPipeline() {
  const open = deals.filter((d) => d.stage !== "won" && d.stage !== "lost");
  const pipeline = open.reduce((sum, d) => sum + d.value, 0);

  return (
    <div className="rounded-xl border">
      <div className="flex items-center justify-between border-b px-4 py-3">
        <h2 className="text-sm font-semibold">Pipeline</h2>
        <p className="text-sm text-muted-foreground">
          Open value <span className="font-medium text-foreground tabular-nums">{usd(pipeline)}</span>
        </p>
      </div>
      <Table>
        <TableHeader className="sticky top-0 bg-background">
          <TableRow>
            <TableHead>Company</TableHead>
            <TableHead>Stage</TableHead>
            <TableHead>Owner</TableHead>
            <TableHead className="text-right">Value</TableHead>
            <TableHead className="text-right">Close</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {deals.map((d) => (
            <TableRow key={d.id} className="cursor-pointer">
              <TableCell className="font-medium">{d.company}</TableCell>
              <TableCell>
                <Badge variant="secondary" className={cn("font-medium", STAGE[d.stage].className)}>
                  {STAGE[d.stage].label}
                </Badge>
              </TableCell>
              <TableCell>
                <Avatar className="h-6 w-6">
                  <AvatarFallback className="text-[10px]">{d.owner}</AvatarFallback>
                </Avatar>
              </TableCell>
              <TableCell className="text-right tabular-nums">{usd(d.value)}</TableCell>
              <TableCell className="text-right text-muted-foreground">{d.closeDate}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}
